<!DOCTYPE html>
<html lang="en">
  	<head>
	    <title>ReViTa Tool</title>
	    <meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″>
	    
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="">
	    <meta name="author" content="">

	    <!-- v= para evitar cache -->
	    <link rel="stylesheet" href="css/pure-min.css"> 
		<link href="css/restyle.css" rel="stylesheet">	


	    <!-- Bootstrap core CSS -->
	    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
		
		<!-- Font Awesome -->
		<link href="css/font-awesome.min.css" rel="stylesheet">

		<!-- ionicons -->
		<link href="css/ionicons.min.css" rel="stylesheet">
		
		<!-- Morris -->
		<link href="css/morris.css" rel="stylesheet"/>	

		<!-- Datepicker -->
		<link href="css/datepicker.css" rel="stylesheet"/>	

		<!-- Animate -->
		<link href="css/animate.min.css" rel="stylesheet">

		<!-- Owl Carousel -->
		<link href="css/owl.carousel.min.css" rel="stylesheet">
		<link href="css/owl.theme.default.min.css" rel="stylesheet">

		<!-- datatable -->
		<link href="css/dataTables.bootstrap.css" rel="stylesheet">
		
		<!-- Simplify -->
		<link href="css/simplify.min.css" rel="stylesheet">


	
  	</head>

  	<body class="overflow-hidden">
		<div class="wrapper preload">
			<div class="sidebar-right">
				<div class="sidebar-inner scrollable-sidebar">
					<div class="sidebar-header clearfix">
						<input class="form-control dark-input" placeholder="Search" type="text">
						<div class="btn-group pull-right">
							<a href="#" class="sidebar-setting" data-toggle="dropdown"><i class="fa fa-cog fa-lg"></i></a>
							<ul class="dropdown-menu pull-right flipInV">
								<li><a href="#"><i class="fa fa-circle text-danger"></i><span class="m-left-xs">Busy</span></a></li>
								<li><a href="#"><i class="fa fa-circle-o"></i><span class="m-left-xs">Turn Off Chat</span></a></li>
							</ul>
						</div>
					</div>
					<div class="title-block">
						Group Chat
					</div>
					<div class="content-block">
						<ul class="sidebar-list">
							<li>
								<a href="#">
									<i class="fa fa-circle-o text-success"></i><span class="m-left-xs">Close Friends</span>
								</a>
							</li>
							<li>
								<a href="#">
									<i class="fa fa-circle-o text-success"></i><span class="m-left-xs">Business</span>
								</a>
							</li>
						</ul>
					</div>
					<div class="title-block">
						Favorites
					</div>
					<div class="content-block">
						<ul class="sidebar-list">
							<li>
								<a href="#" class="clearfix">
									<img src="images/profile/profile2.jpg" class="img-circle" alt="user avatar">
									<div class="chat-detail m-left-sm">
										<div class="chat-name">
											John Doe
										</div>
										<div class="chat-message">
											Where are you?
										</div>
									</div>
									<div class="chat-status">
										<i class="fa fa-circle-o text-success"></i>
									</div>
									<div class="chat-alert">
										<span class="badge badge-purple bounceIn animation-delay2">2</span>
									</div>
								</a>
							</li>
							<li>
								<a href="#" class="clearfix">
									<img src="images/profile/profile3.jpg" class="img-circle" alt="user avatar">
									<div class="chat-detail m-left-sm">
										<div class="chat-name">
											Jane Doe
										</div>
										<div class="chat-message">
											Hello
										</div>
									</div>
									<div class="chat-status">
										<i class="fa fa-circle-o text-success"></i>
									</div>
									<div class="chat-alert">
										<span class="badge badge-info bounceIn animation-delay2">1</span>
									</div>
								</a>
							</li>
							<li>
								<a href="#" class="clearfix">
									<img src="images/profile/profile4.jpg" class="img-circle" alt="user avatar">
									<div class="chat-detail m-left-sm">
										<div class="chat-name">
											John Doe
										</div>
										<div class="chat-message">
											See you again next week.
										</div>
									</div>
									<div class="chat-status">
										<i class="fa fa-circle-o text-danger"></i>
									</div>
									<div class="chat-alert">
										<i class="fa fa-check text-success"></i>
									</div>
								</a>
							</li>
							<li>
								<a href="#" class="clearfix">
									<img src="images/profile/profile5.jpg" class="img-circle" alt="user avatar">
									<div class="chat-detail m-left-sm">
										<div class="chat-name">
											John Doe
										</div>
										<div class="chat-message">
											Hello, Are you there?
										</div>
									</div>
									<div class="chat-status">
										<i class="fa fa-circle-o text-danger"></i>
									</div>
									<div class="chat-alert">
										<i class="fa fa-reply"></i>
									</div>
								</a>
							</li>
						</ul>
					</div>
					<div class="title-block">
						More friends
					</div>
					<div class="content-block">
						<ul class="sidebar-list">
							<li>
								<a href="#" class="clearfix">
									<img src="images/profile/profile6.jpg" class="img-circle" alt="user avatar">
									<div class="chat-detail m-left-sm">
										<div class="chat-name">
											John Doe
										</div>
										<div class="chat-message">
											Where are you?
										</div>
									</div>
									<div class="chat-status">
										<i class="fa fa-circle-o text-success"></i>
									</div>
									<div class="chat-alert">
										<span class="badge badge-success bounceIn animation-delay2">2</span>
									</div>
								</a>
							</li>
							<li>
								<a href="#" class="clearfix">
									<img src="images/profile/profile7.jpg" class="img-circle" alt="user avatar">
									<div class="chat-detail m-left-sm">
										<div class="chat-name">
											Jane Doe
										</div>
										<div class="chat-message">
											Hello
										</div>
									</div>
									<div class="chat-status">
										<i class="fa fa-circle-o text-success"></i>
									</div>
									<div class="chat-alert">
										<span class="badge badge-danger bounceIn animation-delay2">1</span>
									</div>
								</a>
							</li>
							<li>
								<a href="#" class="clearfix">
									<img src="images/profile/profile8.jpg" class="img-circle" alt="user avatar">
									<div class="chat-detail m-left-sm">
										<div class="chat-name">
											John Doe
										</div>
										<div class="chat-message">
											See you again next week.
										</div>
									</div>
									<div class="chat-status">
										<i class="fa fa-circle-o text-danger"></i>
									</div>
									<div class="chat-alert">
										<i class="fa fa-check text-success"></i>
									</div>
								</a>
							</li>
							<li>
								<a href="#" class="clearfix">
									<img src="images/profile/profile9.jpg" class="img-circle" alt="user avatar">
									<div class="chat-detail m-left-sm">
										<div class="chat-name">
											John Doe
										</div>
										<div class="chat-message">
											Hello, Are you there?
										</div>
									</div>
									<div class="chat-status">
										<i class="fa fa-circle-o text-danger"></i>
									</div>
									<div class="chat-alert">
										<i class="fa fa-reply"></i>
									</div>
								</a>
							</li>
						</ul>
					</div>
				</div><!-- sidebar-inner -->
			</div><!-- sidebar-right -->

			<?php if(isset($_GET['id_sos'])){ ?>
			<header class="top-nav">
				<?php } else{?>
				<header class="top-nav sidebar-mini">
				<?php }?>
				<div class="top-nav-inner">
					<div class="nav-header">

						<button type="button" class="navbar-toggle pull-left sidebar-toggle" id="sidebarToggleSM">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						
						<a href="index.php" class="brand">
							<i class="fa fa-bullseye"></i><span class="brand-name">ReViTa Tool</span>
						</a>
					</div>
					<div class="nav-container">
						<button type="button" class="navbar-toggle pull-left sidebar-toggle" id="sidebarToggleLG">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<div class="pull-right m-right-sm">
							<ul class="nav-notification">
								<li>
									<a href="#" data-toggle="dropdown"><i class="fa fa-bell fa-lg"></i></a>
									<span class="badge badge-info bounceIn animation-delay6 active">4</span>
									<ul class="dropdown-menu notification dropdown-3 pull-right">
										<li><a href="#">You have 5 new notifications</a></li>					  
										<li>
											<a href="#">
												<span class="notification-icon bg-warning">
													<i class="fa fa-warning"></i>
												</span>
												<span class="m-left-xs">Server #2 not responding.</span>
												<span class="time text-muted">Just now</span>
											</a>
										</li>
										<li>
											<a href="#">
												<span class="notification-icon bg-success">
													<i class="fa fa-plus"></i>
												</span>
												<span class="m-left-xs">New user registration.</span>
												<span class="time text-muted">2m ago</span>
											</a>
										</li>
										<li>
											<a href="#">
												<span class="notification-icon bg-danger">
													<i class="fa fa-bolt"></i>
												</span>
												<span class="m-left-xs">Application error.</span>
												<span class="time text-muted">5m ago</span>
											</a>
										</li>
										<li>
											<a href="#">
												<span class="notification-icon bg-success">
													<i class="fa fa-usd"></i>
												</span>
												<span class="m-left-xs">2 items sold.</span>
												<span class="time text-muted">1hr ago</span>
											</a>
										</li>
										<li>
											<a href="#">
												<span class="notification-icon bg-success">
													<i class="fa fa-plus"></i>
												</span>
												<span class="m-left-xs">New user registration.</span>
												<span class="time text-muted">1hr ago</span>
											</a>
										</li>
										<li><a href="#">View all notifications</a></li>					  
									</ul>
								</li>
							</ul>
						</div>
					</div>
				</div><!-- ./top-nav-inner -->	
			</header>
			<?php if(isset($_GET['id_sos']) and $_GET['id_sos'] != 0){ ?>
			<aside class="sidebar-menu fixed">
				<?php } else{?>
				<aside class="sidebar-menu fixed sidebar-mini">
					<?php }?>
				<div class="sidebar-inner scrollable-sidebar">
					<div class="main-menu">
						<ul class="accordion">
							<li class="menu-header">
								Main Menu
							</li>
							<li class="bg-palette2 active">
								<a href="index.php">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-home fa-lg"></i></span>
										<span class="text m-left-sm">Home</span>
									</span>
									<span class="menu-content-hover block">
										Home
									</span>
								</a>
							</li>
							<?php
							if(isset($_GET['id_sos']) and $_GET['id_sos'] != 0 ){
							
							?>
							<li class="bg-palette3">
									<a href="show_sos.php?id_sos=<?php echo $_GET['id_sos'];?>">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-desktop fa-lg"></i></span>
										<span class="text m-left-sm"><!--SoS Panel--><?php echo $sos['name']; ?></span>
									</span>
									<span class="menu-content-hover block">
										Panel
									</span>
								</a>
							</li>

							<li class="bg-palette1">
								<!--<a href="show_diagram.php?id_sos=<?php echo $sos['id_sos'];?>">-->
									<a href="show_diagram.php?id_sos=<?php echo $_GET['id_sos'];?>">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-bars fa-lg"></i></span>
										<span class="text m-left-sm">Mission decomposition</span>
									</span>
									<span class="menu-content-hover block">
										Mission decomp.
									</span>
								</a>
							</li>

							<li class="bg-palette1">
								<a href="show_requirements.php?id_sos=<?php echo $_GET['id_sos'];?>">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-list fa-lg"></i></span>
										<span class="text m-left-sm">Mission requirements</span>
									</span>
									<span class="menu-content-hover block">
										Mission requi.
									</span>
								</a>
							</li>
							<li class="bg-palette3">
								<a href="show_sois.php?id_sos=<?php echo $_GET['id_sos']; ?>">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-asterisk fa-lg"></i></span>
										<span class="text m-left-sm">States of interest</span>
									</span>
									<span class="menu-content-hover block">
										States of interest
									</span>
								</a>
							</li>
						
							<li class="bg-palette4">
								<a href="show_obspoints.php?id_sos=<?php echo $_GET['id_sos']; ?>">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-circle fa-lg"></i></span>
										<span class="text m-left-sm">Observation points</span>
									</span>
									<span class="menu-content-hover block">
										Obs. points
									</span>
								</a>
							</li>
							<li class="bg-palette1">
								<a href="define_invariant.php?id_sos=<?php echo $_GET['id_sos']; ?>">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-certificate fa-lg"></i></span>
										<span class="text m-left-sm">M. requirements for TAC</span>
									</span>
									<span class="menu-content-hover block">
										M. req. for TAC
									</span>
								</a>
							</li>

							<li class="bg-palette2">
								<a href="show_transient_configuration.php?id_sos=<?php echo $_GET['id_sos']; ?>">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-tags fa-lg"></i></span>
										<span class="text m-left-sm">TACs</span>
									</span>
									<span class="menu-content-hover block">
										TACs
									</span>
								</a>
							</li>

				
							<?php

						}else{?>
							
							<!--<li class="bg-palette4">
								<a href="landing/landing.html">
									<span class="menu-content block">
										<span class="menu-icon"><i class="block fa fa-cog fa-lg"></i></span>
										<span class="text m-left-sm">Framework tutorial</span>
										<small class="badge badge-danger badge-square bounceIn animation-delay5 m-left-xs">	5</small>
									</span>
									<span class="menu-content-hover block">
										Framework tutorial
									</span>
								</a>
							</li>-->
							<?php 
						};
							?>
						
						</ul>
					</div>	
					
				</div><!-- sidebar-inner -->
			</aside>
			
			<?php if(isset($_GET['id_sos'])){ ?>
			<div class="main-container">
				<?php } else{?>
			<div class="main-container sidebar-mini">
					<?php }?>
				<div class="padding-md">
					
					<!-- conteúdo aqui -->

